name: 🚀 Deploy website on push

on:
    push:
        branches:
            - main
    
    workflow_dispatch:
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/bib
          chmod 600 ~/.ssh/bib

      - name: Test SSH
        run: |
          ssh -i ~/.ssh/bib -o StrictHostKeyChecking=no -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }} "echo conectado"

      - name: Deploy via rsync
        run: |
          rsync -rlgoDzvc --delete \
          -e "ssh -i ~/.ssh/bib -p ${{ secrets.FTP_PORT }} -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }}:./public_html/biblioteca